apiVersion : apps/v1
kind: Deployment
metadata:
   name: botdeploy2
   labels:
    app  : testbot 
spec:
    replicas: 1
    selector:
      matchLabels:
           project: testbot  
    template:
     metadata: 
      labels: 
       project: testbot  
     spec: 
      containers:
      - name : botdeploy
        image: 150762/bot1:latest
        ports:
        - containerPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myautoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: botdeploy2
  minReplicas: 2
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 25
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 25
 
